image:
  repository: cr.yandex/crplg5rlmq59dfl3s7if
  tag: "1.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: registry-key
nameOverride: "devops-diplom-app"
fullnameOverride: "devops-diplom-app"

service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

ingress:
  enabled: true
  hosts:
    - paths:
      - path: /devops-diplom-app
        pathType: Prefix
  tls: []
